# permissions for end users to edit schedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduler-editor-role
rules:
- apiGroups:
  - cache.lilq.cn
  resources:
  - schedulers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cache.lilq.cn
  resources:
  - schedulers/status
  verbs:
  - get
