# permissions for end users to view schedulers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scheduler-viewer-role
rules:
- apiGroups:
  - cache.lilq.cn
  resources:
  - schedulers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cache.lilq.cn
  resources:
  - schedulers/status
  verbs:
  - get
